# (empty) ConfigMap utilised by the nginx controller
# No additional configuration set at present
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-lb-config
  namespace: nginx
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
data:
  #use-geoip2: "true"
  use-geoip: "true"
  #server-snippet: if ($geoip2_city_country_code = "GB") { return 444; }  

  location-snippet:  |
                     #add_header X-GeoCountry $geoip2_city_country_name;
                     #add_header X-GeoCode $geoip2_city_country_code;
                     #add_header X-GeoCity $geoip2_city;
                     #add_header X-GeoLat $geoip2_latitude;
                     #add_header X-GeoRegion $geoip2_region_name;
                     add_header X-GeoCity $geoip_country_code;
                     add_header X-Test "Hi there";
                     add_header X-Addr $remote_addr;